# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdbac4e7b437c28cd48605ab67f56e2a4683e95178d72d624f465adc29d6fad393f935a5b888293ceba9533deb372fde0f4fb9806d0c1699e0be015b048c10d1

test:
  secret_key_base: 71dc7591544b8bacd34a94e5c7d1b60d7390123de95108185a3df692d0b64dd533cdf208c2258d77cf6e935a16f7a9a97f09cf19dd201c5b7b8a44cd530a8b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
